import type { NextPage } from "next";
import Head from "next/head";
import List from "./components/List";

const Home: NextPage = () => {
  return (
    <div className="mx-auto font bg-slate-50">
      <Head>
        <title>Actor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl text-black text-center p-10 font-bold">Actor</h1>
      <List></List>
    </div>
  );
};

export default Home;
